openapi: 3.0.3
info:
  title: Belajar REST API 
  version: "1.0"
servers:
- url: http://localhost:3000
paths:
  /users:
    get:
      description: end point untuk mendapat semua user
      parameters: []
      responses:
        "200":
          content:
            aplication/json:
              schema:
                items:
                  $ref: '#/components/schemas/user'
                type: array
          description: Berhasil
        "500":
          description: server gagal
        "403":
          description: tidak di ijinkan
  /user/{id}:
    delete:
      description: end point untuk menghapus user berdasarkan id
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          description: Berhasil
        "500":
          description: server gagal
        "403":
          description: akses ditolak/tidak di ijinkan
    get:
      description: endpoint untuk mendapatkan user sesuai id
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            aplication/json:
              schema:
                items:
                  $ref: '#/components/schemas/user'
                type: array
          description: Berhasil
        "500":
          description: server gagal
        "403":
          description: akses ditolak/tidak di ijinkan
    put:
      description: endpoint untuk mengubah data user bedasarkan id
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      - explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: email
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: age
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            aplication/json:
              schema:
                items:
                  $ref: '#/components/schemas/user'
                type: array
          description: Berhasil
components:
  schemas:
    user:
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        age:
          type: integer
        creatdAt:
          type: string
        updatedAt:
          type: string
      type: object